djangojokes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import private_storage.urls

urlpatterns = [
    # Admin
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    # User Management
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),

    # Private media
    path('media/private/', include(private_storage.urls)),

    # Local Apps
    path('jobs/', include('jobs.urls')),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path

from .views import JobAppView, JobAppThanksView

app_name = 'jobs'
urlpatterns = [
    path('job-app/', JobAppView.as_view(), name='app'),
    path('job-app/thanks/', JobAppThanksView.as_view(), name='thanks'),
]

jokes/urls.py
from django.urls import path
from .views import (JokeCreateView, JokeListView, JokeDeleteView,
                    JokeDetailView,  JokeUpdateView)

app_name = 'jokes'
urlpatterns = [
    path('joke/<slug>/update/', JokeUpdateView.as_view(), name='update'),
    path('joke/<slug>/delete/', JokeDeleteView.as_view(), name='delete'),
    path('joke/create/', JokeCreateView.as_view(), name='create'),
    path('joke/<slug>/', JokeDetailView.as_view(), name='detail'),
    path('', JokeListView.as_view(), name='list'),
]

pages/urls.py
from django.urls import path

from .views import AboutUsView, HomePageView

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/f804978a2a.js" crossorigin="anonymous"></script>
<title>{% block title %}{% endblock %} | Django Jokes</title>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'pages:homepage' %}">Django Jokes</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-expanded="false"
      aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pages:homepage' %}">Home 
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jokes:list' %}">Jokes</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
        </li>
      {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
            role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Me
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'my-account' %}">My Account</a>
            <a class="dropdown-item" href="#">My Django Jokes</a>
            <div class="dropdown-divider"></div>
            <form method="post" action="{% url 'account_logout' %}">
              {% csrf_token %}
              <button class="btn dropdown-item">Log out</button>
            </form>
          </div>
        </li>
      {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search"
        placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          Search
        </button>
      </form>
    </div>
  </nav>
</header>
<main class="m-4">
  {% if messages %}
    <ul>
      {% for message in messages %}
      <div class="alert message{{ message.tags }} alert-dismissible" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="close" data-dismiss="alert"
            aria-label="Close">
            <i class="fas fa-window-close"></i>
          </button>
        </div>
      {% endfor %}
    </ul>
  {% endif %}
  {% block main %}<h2>Welcome!</h2>{% endblock %}
</main>
<footer class="fixed-bottom bg-light row">
    <div class="col">
      <div class="float-right m-1 mr-2">Copyright &copy; 2020 Django Jokes.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'pages:about-us' %} ">About</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
  </nav>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
</body>
</html>

templates/password_change.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Change Password{% endblock title %}

{% block main %}
<div class="card border-primary m-auto mb-3" style="max-width: 30rem">
  <div class="card-header text-center">Change Password</div>
  <div class="card-body">
    <form method="post" action="{% url 'account_change_password' %}">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="form-control btn btn-primary">CHANGE PASSWORD</button>
    </form>
  </div>
</div>

{% endblock %}